# Chu kỳ Prometheus thu thập (scrape) metrics từ các target
global:
  scrape_interval: 15s

# Các file chứa alert rules
rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Danh sách các nguồn metrics mà Prometheus sẽ thu thập
scrape_configs:

  # Thu thập metrics của chính Prometheus
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  # Thu thập metrics của máy chủ/EC2
  # Node Exporter cung cấp CPU, RAM, Disk, Network,...
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100

  # Thu thập metrics liên quan đến các Docker container
  # Docker Exporter cung cấp thông tin phục vụ giám sát container
  - job_name: docker-exporter
    static_configs:
      - targets:
          - docker-exporter:9713

  # Kiểm tra HTTPS và khả năng truy cập của application
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
        - http_200
    static_configs:
      - targets:
          - https://devsecops-mobile.duckdns.org/health/db
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target

      - source_labels:
          - __param_target
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115
